<?php

namespace AppBundle\Repository;

/**
 * AdvertisementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertisementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserByAdvUserId($advUserId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM AppBundle:User u
            JOIN u.adverts a
            WHERE a.user = :id'
            )->setParameter('id', $advUserId);
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
